
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 30 18:53:03 IST 2012
//----------------------------------------------------

package IC.Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 8;
  public static final int LCBR = 20;
  public static final int LTE = 26;
  public static final int UMINUS = 43;
  public static final int INTEGER = 46;
  public static final int SEMI = 38;
  public static final int CONTINUE = 7;
  public static final int INT = 17;
  public static final int MINUS = 27;
  public static final int STATIC = 39;
  public static final int LT = 25;
  public static final int LP = 24;
  public static final int COMMA = 6;
  public static final int CLASS = 5;
  public static final int RP = 37;
  public static final int PLUS = 33;
  public static final int MULTIPLY = 29;
  public static final int QUOTE = 49;
  public static final int ASSIGN = 2;
  public static final int IF = 16;
  public static final int THIS = 41;
  public static final int ID = 48;
  public static final int DOT = 9;
  public static final int EOF = 0;
  public static final int BOOLEAN = 3;
  public static final int RETURN = 36;
  public static final int RCBR = 35;
  public static final int LB = 19;
  public static final int LAND = 18;
  public static final int EQUAL = 11;
  public static final int TRUE = 42;
  public static final int NEW = 31;
  public static final int error = 1;
  public static final int RB = 34;
  public static final int LOR = 23;
  public static final int NULL = 32;
  public static final int MOD = 28;
  public static final int BREAK = 4;
  public static final int VOID = 44;
  public static final int GTE = 15;
  public static final int ELSE = 10;
  public static final int WHILE = 45;
  public static final int NEQUAL = 30;
  public static final int CLASS_ID = 47;
  public static final int EXTENDS = 12;
  public static final int STRING = 40;
  public static final int LNEG = 22;
  public static final int FALSE = 13;
  public static final int GT = 14;
  public static final int LENGTH = 21;
}

