
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 30 18:56:18 IST 2012
//----------------------------------------------------

package IC.Parser;

/** CUP generated class containing symbol constants. */
public class symLibrary {
  /* terminals */
  public static final int CLASS = 3;
  public static final int LCBR = 7;
  public static final int INT = 5;
  public static final int LP = 8;
  public static final int SEMI = 12;
  public static final int RP = 11;
  public static final int ID = 17;
  public static final int STATIC = 13;
  public static final int LB = 6;
  public static final int BOOLEAN = 2;
  public static final int RB = 9;
  public static final int STRING = 14;
  public static final int COMMA = 4;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int CLASS_ID = 16;
  public static final int VOID = 15;
  public static final int RCBR = 10;
}

